Repository FESP-TEAM-1/beta-frontend, pull requests merged in 2023-12, with the labels that each got.

#5 bfm/page-main: global css 추가 및 공통 컴포넌트 마크업 및 스타일
  package-lock.json
  package.json
  public/card-image.png
  public/concert-img.jpg
  public/concert-img2.jpg
  public/concert-img3.jpg
  src/assets/ticket-before.svg
  src/components/common/BasicCard/BasicCard.module.css
  src/components/common/BasicCard/BasicCard.tsx
  src/components/common/FilterButton/FilterButton.module.css
  src/components/common/FilterButton/FilterButton.tsx
  src/global.css
Labels: ⚙️ 개발환경, 🎨 디자인

#6 bfm/page-detail: 공통 컴포넌트 및 상세 페이지 일부 컴포넌트 마크업 및 스타일
  package-lock.json
  package.json
  src/assets/like.svg
  src/components/common/Carousel/Carousel.module.css
  src/components/common/Carousel/Carousel.tsx
  src/components/common/SelectBox/SelectBox.module.css
  src/components/common/SelectBox/SelectBox.tsx
  src/components/common/index.tsx
  src/components/detail/LikeButton/LikeButton.module.css
  src/components/detail/LikeButton/LikeButton.tsx
  src/components/detail/SubMenu/SubMenu.module.css
  src/components/detail/SubMenu/SubMenu.tsx
  src/components/detail/index.tsx
  src/vite-env.d.ts
  svg.d.ts
Labels: 🎨 디자인

#7 bfm/page-login: 공통 컴포넌트 Button, InputField, SignForm / 로그인 페이지 마크업 및 디자인 / 절대 경로 수정
  src/Router.tsx
  src/assets/icon-check.svg
  src/components/common/Button/Button.module.css
  src/components/common/Button/Button.tsx
  src/components/common/InputField/InputField.module.css
  src/components/common/InputField/InputField.tsx
  src/components/common/SignForm/SignForm.module.css
  src/components/common/SignForm/SignForm.tsx
  src/components/common/index.tsx
  src/pages/Login/LoginPage.module.css
  src/pages/Login/LoginPage.tsx
  src/utils/passwordCheck.ts
  tsconfig.json
  vite.config.ts
Labels: ⚙️ 개발환경, 🎨 디자인

#8 bfm/page-main: Header, NavBar, Carousel 등 컴포넌트 마크업 및 스타일
  package-lock.json
  src/assets/next-arrow.png
  src/assets/prev-arrow.png
  src/components/common/BasicCard/BasicCard.module.css
  src/components/common/Carousel/Carousel.module.css
  src/components/common/Carousel/Carousel.tsx
  src/components/common/Carousel/slick.css
  src/components/common/index.tsx
  src/components/layouts/Header/Header.module.css
  src/components/layouts/Header/Header.tsx
  src/components/layouts/NavBar/NavBar.module.css
  src/components/layouts/NavBar/NavBar.tsx
  src/components/layouts/index.tsx
  src/components/main/Banner/Banner.module.css
  src/components/main/Banner/Banner.tsx
  src/global.css
Labels: ♻️ 리팩토링, 🎨 디자인

#10 bfm/page-signup : 공통 컴포넌트 SignForm 추가 및 회원가입 페이지 마크업 및 디자인
  src/components/common/InputField/InputField.module.css
  src/components/common/InputField/InputField.tsx
  src/components/common/InputFieldGroup/InputFieldGroup.module.css
  src/components/common/InputFieldGroup/InputFieldGroup.tsx
  src/components/common/InputFieldGroup/InputFieldGroupType.ts
  src/components/common/SignForm/SignForm.tsx
  src/components/common/index.tsx
  src/pages/Login/LoginPage.tsx
  src/pages/Signup/SignupPage.module.css
  src/pages/Signup/SignupPage.tsx
  src/utils/dateSelect.ts
  src/utils/emailCheck.ts
  src/utils/passwordCheck.ts
Labels: ♻️ 리팩토링, 🎨 디자인

#11 bfm/page-main: 메인페이지 컴포넌트 마크업 및 스타일
  public/story-img.jpg
  src/App.tsx
  src/assets/plus.svg
  src/components/common/Button/Button.module.css
  src/components/common/Button/Button.tsx
  src/components/common/FilterButton/FilterButton.tsx
  src/components/layouts/Header/Header.module.css
  src/components/layouts/NavBar/NavBar.module.css
  src/components/layouts/NavBar/NavBar.tsx
  src/components/main/CalendarSection/CalendarSection.module.css
  src/components/main/CalendarSection/CalendarSection.tsx
  src/components/main/DateButton/DateButton.module.css
  src/components/main/DateButton/DateButton.tsx
  src/components/main/StoryCard/Story.module.css
  src/components/main/StoryCard/Story.tsx
  src/components/main/StorySection/StorySection.module.css
  src/components/main/StorySection/StorySection.tsx
  src/components/main/index.tsx
  src/global.css
  src/pages/Main/MainPage.tsx
  src/utils/getStringDate.ts
  src/utils/getTodayStringDate.ts
Labels: 🎨 디자인, 🐞 버그, 🛠️ 기능개발

#18 feat/modal: Modal 컴포넌트 열때 root 자식으로 추가되도록 createPortal 추가
  src/components/common/Modal/Modal.tsx
Labels: 🛠️ 기능개발

#16 bfm/page-mypage : 마이페이지 라우터 설정 및 마크업 / 네비게이션 바 추가
  src/Router.tsx
  src/components/mypage/LikeManage/LikeManage.module.css
  src/components/mypage/LikeManage/LikeManage.tsx
  src/components/mypage/NavigationBar/NavigationBar.module.css
  src/components/mypage/NavigationBar/NavigationBar.tsx
  src/components/mypage/PostManage/PostManage.module.css
  src/components/mypage/PostManage/PostManage.tsx
  src/components/mypage/Profile/Profile.module.css
  src/components/mypage/Profile/Profile.tsx
  src/components/mypage/Reservation/Reservation.module.css
  src/components/mypage/Reservation/Reservation.tsx
  src/components/mypage/ReservationManage/ReservationManage.module.css
  src/components/mypage/ReservationManage/ReservationManage.tsx
  src/components/mypage/ReviewManage/ReviewManage.module.css
  src/components/mypage/ReviewManage/ReviewManage.tsx
  src/components/mypage/StoryManage/StoryManage.module.css
  src/components/mypage/StoryManage/StoryManage.tsx
  src/components/mypage/index.tsx
  src/pages/Mypage/Mypage.module.css
  src/pages/Mypage/Mypage.tsx
Labels: 🎨 디자인

#19 bfm/page-detail: 상세 페이지 - 방명록 섹션 마크업 및 스타일
  src/Router.tsx
  src/assets/ellipsis-profile.svg
  src/assets/icon-ellipsis-vertical.png
  src/components/common/Button/Button.module.css
  src/components/common/index.tsx
  src/components/detail/GuestAccess/GuestAccess.module.css
  src/components/detail/GuestAccess/GuestAccess.tsx
  src/components/detail/InfoSection/InfoSection.module.css
  src/components/detail/InfoSection/InfoSection.tsx
  src/components/detail/InfoSection/LocationMap.tsx
  src/components/detail/ReviewForm/ReviewForm.module.css
  src/components/detail/ReviewForm/ReviewForm.tsx
  src/components/detail/ReviewItem/ReviewItem.module.css
  src/components/detail/ReviewItem/ReviewItem.tsx
  src/components/detail/ReviewSection/ReviewSection.module.css
  src/components/detail/ReviewSection/ReviewSection.tsx
  src/components/detail/SubMenuBar/SubMenuBar.module.css
  src/components/detail/SubMenuBar/SubMenuBar.tsx
  src/components/detail/SubMenuSection/SubMenuSection.tsx
  src/components/detail/index.tsx
  src/components/main/CalendarSection/CalendarSection.module.css
  src/pages/Detail/DetaiPage.module.css
  src/pages/Detail/DetailPage.tsx
  src/stores/useDetailDataStore.ts
  src/stores/useModalStore.ts
  src/utils/getElapsedTime.ts
Labels: ♻️ 리팩토링, 🎨 디자인

#22 bfm/page-detail-reservation-modal: 공통 컴포넌트 RadioButton, Checkbox 마크업 및 스타일 / 예약 모달창 내부 기본 마크업 및 스타일
  src/assets/checkbox-checked.svg
  src/assets/checkbox.svg
  src/assets/radio-checked.svg
  src/assets/radio.svg
  src/components/common/Button/Button.tsx
  src/components/common/CheckBox/CheckBox.module.css
  src/components/common/CheckBox/CheckBox.tsx
  src/components/common/InputField/InputField.tsx
  src/components/common/InputFieldGroup/InputFieldGroup.tsx
  src/components/common/InputFieldGroup/InputFieldGroupType.ts
  src/components/common/RadioButtonGroup/RadioButtonGroup.module.css
  src/components/common/RadioButtonGroup/RadioButtonGroup.tsx
  src/components/common/index.tsx
  src/components/detail/ReservationSection/ReservationSection.module.css
  src/components/detail/ReservationSection/ReservationSection.tsx
  src/components/detail/index.tsx
  src/global.css
  src/hooks/useInputs.tsx
Labels: ♻️ 리팩토링, 🎨 디자인, 🙋🏻 질문, 🛠️ 기능개발

#23 bfm/page-main: 메인페이지 반응형 구현 및 스토리 관련 부분 마크업 및 스타일
  src/assets/img-upload.svg
  src/components/common/BasicCard/BasicCard.tsx
  src/components/common/Button/Button.module.css
  src/components/common/Carousel/Carousel.tsx
  src/components/common/Carousel/slick.css
  src/components/common/FilterButton/FilterButton.module.css
  src/components/common/Modal/Modal.module.css
  src/components/common/Modal/Modal.tsx
  src/components/common/TagInput/TagInput.tsx
  src/components/common/index.tsx
  src/components/main/CalendarSection/CalendarSection.module.css
  src/components/main/CalendarSection/CalendarSection.tsx
  src/components/main/DateButton/DateButton.module.css
  src/components/main/StorySection/StorySection.module.css
  src/components/main/StorySection/StorySection.tsx
  src/components/main/StoryUploadModal/StoryUploadModal.module.css
  src/components/main/StoryUploadModal/StoryUploadModal.tsx
  src/components/main/StoryViewModal/StoryViewModal.module.css
  src/components/main/StoryViewModal/StoryViewModal.tsx
  src/components/main/index.tsx
  src/global.css
  src/hooks/index.tsx
  src/hooks/usePreventScroll.tsx
Labels: 🎨 디자인, 🛠️ 기능개발

#24 bfm/page-postmanage: 게시글 관리페이지(관리자) 마크업 및 스타일
  src/assets/comment.svg
  src/components/mypage/NavigationBar/NavigationBar.tsx
  src/components/mypage/PostManage/PostManage.module.css
  src/components/mypage/PostManage/PostManage.tsx
  src/pages/Mypage/Mypage.module.css
Labels: 🎨 디자인

#25 bfm/page-main: Tagify 라이브러리 설치
  package-lock.json
  package.json
Labels: ⚙️ 개발환경

#26 bfm/page-reservation-manage: 예매관리페이지 마크업 및 스타일
  src/components/mypage/ReservationListModal/ReservationListModal.module.css
  src/components/mypage/ReservationListModal/ReservationListModal.tsx
  src/components/mypage/ReservationManage/ReservationManage.module.css
  src/components/mypage/ReservationManage/ReservationManage.tsx
  src/components/mypage/index.tsx
Labels: 🎨 디자인

#27 bfm/page-main-exhibition
  src/Router.tsx
  src/components/common/Filters/Filters.module.css
  src/components/common/Filters/Filters.tsx
  src/components/common/index.tsx
  src/components/mainConcert/index.tsx
  src/components/mainExhibition/ExhibitionListSection/ExhibitionListSection.module.css
  src/components/mainExhibition/ExhibitionListSection/ExhibitionListSection.tsx
  src/components/mainExhibition/index.tsx
  src/pages/MainConcert/MainConcertPage.tsx
  src/pages/MainExhibition/MainExhibitionPage.tsx
  src/pages/index.tsx
Labels: 🎨 디자인

#28 bfm/page-detail-reservation-modal: useModalStore 변경 및 상세 페이지에 모달 스타일 적용
  src/components/common/Modal/Modal.tsx
  src/components/common/index.tsx
  src/components/detail/GuestAccess/GuestAccess.module.css
  src/components/detail/GuestAccess/GuestAccess.tsx
  src/components/detail/ReservationFormModal/ReservationFormModal.module.css
  src/components/detail/ReservationFormModal/ReservationFormModal.tsx
  src/components/detail/ReviewSection/ReviewSection.tsx
  src/components/detail/index.tsx
  src/pages/Detail/DetailPage.tsx
  src/stores/useModalStore.ts
Labels: ♻️ 리팩토링, 🎨 디자인, 🛠️ 기능개발

#29 bfm/page-mypage-post-upload: 관리자 게시글업로드 페이지 마크업 및 스타일
  package-lock.json
  package.json
  src/assets/ImgUploadIcon.svg
  src/components/common/DatePicker/DatePicker.tsx
  src/components/common/Editor/Editor.tsx
  src/components/common/RadioButtonGroup/RadioButtonGroup.module.css
  src/components/common/RadioButtonGroup/RadioButtonGroup.tsx
  src/components/common/index.tsx
  src/components/detail/ReservationFormModal/ReservationFormModal.tsx
  src/components/mypage/PostUpload/PostUpload.module.css
  src/components/mypage/PostUpload/PostUpload.tsx
  src/components/mypage/ReservationForm/ReservationForm.module.css
  src/components/mypage/ReservationForm/ReservationForm.tsx
  src/components/mypage/index.tsx
  src/pages/Mypage/Mypage.module.css
  src/pages/Mypage/Mypage.tsx
Labels: 🎨 디자인, 🛠️ 기능개발

#30 bfm/page-postmanage: 반응형 헤더, 마이페이지 사이드메뉴바구현
  src/assets/menu.svg
  src/assets/navbar-close.svg
  src/components/layouts/Header/Header.module.css
  src/components/layouts/Header/Header.tsx
  src/components/layouts/NavBar/NavBar.module.css
  src/components/mypage/NavigationBar/NavigationBar.module.css
  src/components/mypage/Profile/Profile.module.css
  src/global.css
  src/pages/Mypage/Mypage.module.css
Labels: 🎨 디자인, 🐞 버그

#32 bfm/page-mypagepost-upload: datePicker 스타일 커스텀
  src/assets/icon-calendar.svg
  src/components/common/DatePicker/DatePicker.css
  src/components/common/DatePicker/DatePicker.module.css
  src/components/common/DatePicker/DatePicker.tsx
Labels: 🎨 디자인

#33 bfm/page-detail: 상세 페이지 - 지도 위치마커 커스텀
  src/assets/icon-map-pin.svg
  src/components/detail/InfoSection/LocationMap.tsx
Labels: 🎨 디자인

#34 feat/page-detail: 상세페이지, 정보섹션 및 예매하기 모달창 API 연결
  src/Router.tsx
  src/apis/getShowItemInfo.tsx
  src/apis/getShowReservationInfo.tsx
  src/apis/getUserInfo.tsx
  src/components/common/Button/Button.module.css
  src/components/common/InputFieldGroup/InputFieldGroup.tsx
  src/components/common/InputFieldGroup/InputFieldGroupType.ts
  src/components/common/RadioButtonGroup/RadioButtonGroup.tsx
  src/components/detail/InfoSection/InfoSection.tsx
  src/components/detail/ReservationFormModal/ReservationFormModal.tsx
  src/components/detail/SubMenuSection/SubMenuSection.tsx
  src/hooks/useInputs.tsx
  src/main.tsx
  src/pages/Detail/DetailPage.tsx
  src/stores/useDetailDataStore.ts
  src/stores/useShowItemInfoStore.ts
  src/types/showItemInfo.ts
  src/types/showReservationInfo.ts
  src/types/userInfo.ts
Labels: ♻️ 리팩토링, 🎨 디자인, 🛠️ 기능개발

#35 feat/page-main: 메인페이지 스토리, 공연/전시 정보 API 연결
  src/apis/getShows.ts
  src/apis/getStories.ts
  src/apis/index.ts
  src/components/common/BasicCard/BasicCard.tsx
  src/components/common/Carousel/Carousel.tsx
  src/components/main/CalendarSection/CalendarSection.tsx
  src/components/main/StoryCard/Story.tsx
  src/components/main/StoryCard/StoryCard.module.css
  src/components/main/StoryCard/StoryCard.tsx
  src/components/main/StorySection/StorySection.tsx
  src/components/main/StoryViewModal/StoryViewModal.tsx
  src/components/main/StoryViewModalCard/StoryViewModalCard.module.css
  src/components/main/StoryViewModalCard/StoryViewModalCard.tsx
  src/components/main/index.tsx
  src/stores/useCarouselDragStore.ts
  src/types/index.ts
  src/types/showType.ts
  src/types/storyType.ts
  src/utils/getTxtColorByBgColor.ts
Labels: 🎨 디자인, 🐞 버그, 🛠️ 기능개발

#36 feat/page-main-concert: 메인 공연/전시 페이지 필터값이 바뀔때마다 data fetch 구현
  src/components/common/FilterButton/FilterButton.module.css
  src/components/common/Filters/Filters.tsx
  src/components/mainConcert/ConertListSection/ConcertListSection.tsx
  src/components/mainConcert/TicketCard/TicketCard.tsx
  src/components/mainExhibition/ExhibitionListSection/ExhibitionListSection.tsx
  src/pages/MainConcert/MainConcertPage.tsx
  src/pages/MainExhibition/MainExhibitionPage.tsx
Labels: 🎨 디자인, 🛠️ 기능개발

#37 bfm/responsive: 반응형 관련 스타일 수정
  src/components/common/Button/Button.module.css
  src/components/common/Button/Button.tsx
  src/components/layouts/Header/Header.module.css
  src/components/mypage/NavigationBar/NavigationBar.module.css
  src/components/mypage/PostManage/PostManage.module.css
  src/components/mypage/PostManage/PostManage.tsx
  src/components/mypage/PostUpload/PostUpload.module.css
  src/components/mypage/ReservationManage/ReservationManage.tsx
  src/pages/Mypage/Mypage.module.css
  src/pages/Mypage/Mypage.tsx
Labels: ♻️ 리팩토링, 🎨 디자인

#38 feat/page-main-concert: 메인 공연페이지 필터 버그 고침 및 디자인 수정
  src/components/mainConcert/ConertListSection/ConcertListSection.module.css
  src/components/mainConcert/ConertListSection/ConcertListSection.tsx
  src/components/mainConcert/TicketCard/TicketCard.module.css
  src/components/mainConcert/TicketCard/TicketCard.tsx
Labels: 🎨 디자인, 🐞 버그

#39 feat/page-login : 로그인 API 적용 및 토큰 검증 기능 추가
  src/App.tsx
  src/PrivateRoute.tsx
  src/apis/getVerifyToken.tsx
  src/apis/patchUserLogin.tsx
  src/apis/patchUserLogout.tsx
  src/components/common/SignForm/SignForm.tsx
  src/components/layouts/Header/Header.tsx
  src/hooks/useAuth.tsx
  src/pages/Login/LoginPage.tsx
  src/stores/useLoginStore.ts
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#40 feat/page-main: 메인페이지 배너 api 연결 및 스토리 모달 반응형 구현
  src/apis/getBannerImages.ts
  src/apis/index.ts
  src/components/common/Carousel/Carousel.tsx
  src/components/common/Carousel/slick.css
  src/components/main/Banner/Banner.module.css
  src/components/main/Banner/Banner.tsx
  src/components/main/StoryViewModal/StoryViewModal.module.css
  src/components/main/StoryViewModalCard/StoryViewModalCard.module.css
  src/types/showType.ts
Labels: ♻️ 리팩토링, 🎨 디자인, 🛠️ 기능개발

#41 feat/page-detail: Detail 페이지 type 관련 작업 및 toastify 추가
  package-lock.json
  package.json
  src/apis/getShowInfo.tsx
  src/apis/getShowItemInfo.tsx
  src/apis/getShowReservationInfo.tsx
  src/apis/getShows.ts
  src/apis/getUserInfo.tsx
  src/apis/index.ts
  src/components/common/BasicCard/BasicCard.tsx
  src/components/common/DatePicker/DatePicker.tsx
  src/components/detail/InfoSection/InfoSection.tsx
  src/components/detail/ReservationFormModal/ReservationFormModal.tsx
  src/components/detail/SubMenuSection/SubMenuSection.tsx
  src/components/main/CalendarSection/CalendarSection.tsx
  src/components/mainExhibition/ExhibitionListSection/ExhibitionListSection.tsx
  src/components/mypage/PostUpload/PostUpload.tsx
  src/components/mypage/ReservationForm/ReservationForm.tsx
  src/hooks/useInputs.tsx
  src/main.tsx
  src/pages/Detail/DetailPage.tsx
  src/stores/useShowInfoStore.ts
  src/stores/useShowItemInfoStore.ts
  src/toast.css
  src/types/datePickerInputType.ts
  src/types/formInputsType.ts
  src/types/index.ts
  src/types/memberType.ts
  src/types/showItemInfo.ts
  src/types/showReservationInfoType.ts
  src/types/userReservationFormType.ts
  src/utils/formattingDate.ts
  src/utils/formattingTime.ts
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#42 refactor/mypage-router: 마이페이지 라우팅 방식 변경 (querystring -> pathname)
  src/Router.tsx
  src/components/layouts/Header/Header.tsx
  src/components/mypage/NavigationBar/NavigationBar.tsx
  src/pages/Mypage/Mypage.tsx
Labels: ♻️ 리팩토링

#43 feat/page-signup : 회원가입 기능 추가
  src/apis/getUserInfo.tsx
  src/apis/index.ts
  src/apis/postSignupAPI.tsx
  src/components/common/InputFieldGroup/InputFieldGroup.module.css
  src/components/common/InputFieldGroup/InputFieldGroup.tsx
  src/components/common/InputFieldGroup/InputFieldGroupType.ts
  src/components/common/Timer/Timer.tsx
  src/components/mypage/Profile/Profile.tsx
  src/data/univList.json
  src/pages/Signup/SignupPage.module.css
  src/pages/Signup/SignupPage.tsx
  src/types/SignupBodyType.ts
  src/utils/index.ts
Labels: ♻️ 리팩토링, 🎨 디자인, 🛠️ 기능개발

#44 feat/page-main: 스토리 업로드 기능 구현
  package-lock.json
  package.json
  src/apis/index.ts
  src/apis/postStory.ts
  src/components/common/TagInput/TagInput.tsx
  src/components/main/Banner/Banner.module.css
  src/components/main/Banner/Banner.tsx
  src/components/main/CalendarSection/CalendarSection.module.css
  src/components/main/CalendarSection/CalendarSection.tsx
  src/components/main/CalendarSection/CalendarSectionSkeleton.tsx
  src/components/main/StoryCard/StoryCard.module.css
  src/components/main/StorySection/StorySection.module.css
  src/components/main/StorySection/StorySection.tsx
  src/components/main/StorySection/StorySectionSkeleton.tsx
  src/components/main/StoryUploadModal/StoryUploadModal.module.css
  src/components/main/StoryUploadModal/StoryUploadModal.tsx
  src/components/main/StoryViewModalCard/StoryViewModalCard.tsx
  src/pages/Main/MainPage.tsx
  src/types/storyType.ts
  src/utils/converArrayToObject.ts
  src/utils/reduceImageSize.ts
Labels: 🎨 디자인, 🛠️ 기능개발

#46 feat/page-login : 라우터마다 로그인 검증 로직 추가 및 기존 PrivateRoute 변경
  src/App.tsx
  src/PrivateRoute.tsx
  src/apis/patchUserLogin.tsx
  src/components/layouts/Header/Header.tsx
  src/hooks/useAuth.tsx
  src/stores/useLoginStore.ts
Labels: ♻️ 리팩토링, 🐞 버그

#48 feat/page-mypage-show-upload: 게시글 업로드 POST API 연결
  package-lock.json
  package.json
  src/Router.tsx
  src/apis/postShow.ts
  src/components/common/DatePicker/DatePicker.css
  src/components/common/DatePicker/DatePicker.module.css
  src/components/common/DatePicker/DatePicker.tsx
  src/components/common/DeleteButton/DeleteButton.module.css
  src/components/common/DeleteButton/DeleteButton.tsx
  src/components/common/Editor/Editor.css
  src/components/common/Editor/Editor.tsx
  src/components/common/InputField/InputField.module.css
  src/components/common/InputField/InputField.tsx
  src/components/common/RadioButtonGroup/RadioButtonGroup.module.css
  src/components/common/index.tsx
  src/components/main/StoryUploadModal/StoryUploadModal.tsx
  src/components/mypage/PostManage/PostManage.module.css
  src/components/mypage/PostManage/PostManage.tsx
  src/components/mypage/PostUpload/PostUpload.module.css
  src/components/mypage/PostUpload/PostUpload.tsx
  src/components/mypage/ReservationForm/ReservationForm.module.css
  src/components/mypage/ReservationForm/ReservationForm.tsx
  src/types/index.ts
  src/types/showReservationInfoType.ts
  src/types/showType.ts
  src/utils/convertArrayToObject.ts
  vite.config.ts
Labels: ⚙️ 개발환경, 🐞 버그, 🛠️ 기능개발

#47 feat/page-detail-comment: 댓글 데이터 fetch, 업로드, 수정, 삭제 기능 구현
  src/apis/deleteReview.ts
  src/apis/getReviews.ts
  src/apis/index.ts
  src/apis/patchReview.ts
  src/apis/postReview.ts
  src/components/detail/ReviewEditForm/ReviewEditForm.module.css
  src/components/detail/ReviewEditForm/ReviewEditForm.tsx
  src/components/detail/ReviewForm/ReviewForm.tsx
  src/components/detail/ReviewItem/ReviewItem.module.css
  src/components/detail/ReviewItem/ReviewItem.tsx
  src/components/detail/ReviewSection/ReviewSection.tsx
  src/components/detail/index.tsx
  src/main.tsx
  src/types/index.ts
  src/types/reviewType.ts
Labels: 🎨 디자인, 🛠️ 기능개발

#49 bfm/page-mypage-like : 좋아요 관리 페이지 마크업 및 스타일 및 네비게이션 유저, 관리자 구분 리팩토링
  src/components/mypage/LikeManage/LikeManage.module.css
  src/components/mypage/LikeManage/LikeManage.tsx
  src/components/mypage/NavigationBar/NavigationBar.tsx
  src/pages/Mypage/Mypage.tsx
Labels: ♻️ 리팩토링, 🎨 디자인

#51 feat/page-mypage-like : 마이페이지 좋아요 관리 API 통신 후 출력 및 반응형
  src/apis/getUserLikeList.ts
  src/apis/index.ts
  src/components/mypage/LikeManage/LikeManage.module.css
  src/components/mypage/LikeManage/LikeManage.tsx
Labels: 🛠️ 기능개발

#50 feat/show-upload-location-position: 게시글 업로드 location, position 관련 오픈 API 적용
  index.html
  package-lock.json
  package.json
  src/components/main/Postcode/Postcode.tsx
  src/components/main/index.tsx
  src/components/mypage/PostUpload/PostUpload.module.css
  src/components/mypage/PostUpload/PostUpload.tsx
Labels: 🛠️ 기능개발

#54 feat/page-detail-like: 상세페이지 좋아요, 좋아요 취소 기능 구현
  src/apis/deleteLike.ts
  src/apis/index.ts
  src/apis/postLike.ts
  src/components/detail/InfoSection/InfoSection.tsx
  src/components/detail/LikeButton/LikeButton.tsx
  src/pages/Detail/DetailPage.tsx
  src/types/showType.ts
Labels: 🐞 버그, 🛠️ 기능개발

#53 refactor/toastify: toastify 스타일 Toast Emitter -> Toast Container
  src/components/detail/InfoSection/InfoSection.tsx
  src/main.tsx
  src/toast.css
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#55 feat/page-mypage-show-upload: 게시글 업로드 toast 적용, 유효성 검사 추가, 기타 버그 수정
  src/components/main/Postcode/Postcode.tsx
  src/components/mypage/PostUpload/PostUpload.tsx
  src/utils/formattingDate.ts
Labels: 🐞 버그, 🛠️ 기능개발

#56 bfm/page-mypage-review : 리뷰 페이지 마크업 및 디자인
  src/components/mypage/LikeManage/LikeManage.tsx
  src/components/mypage/NavigationBar/NavigationBar.tsx
  src/components/mypage/ReviewManage/ReviewManage.module.css
  src/components/mypage/ReviewManage/ReviewManage.tsx
  src/components/mypage/ReviewMypageItem/ReviewMypageItem.module.css
  src/components/mypage/ReviewMypageItem/ReviewMypageItem.tsx
  src/utils/isWithinOneDay.ts
Labels: ♻️ 리팩토링, 🎨 디자인

#58 feat/page-detail-like: Delete api body 대신 path parameter로 변경
  src/apis/deleteLike.ts
  src/apis/deleteReview.ts
Labels: 🐞 버그

#57 feat/page-detail: 상세 페이지 InfoSection 소개, 지도관련 작업
  package-lock.json
  package.json
  src/apis/index.ts
  src/components/detail/InfoSection/InfoSection.module.css
  src/components/detail/InfoSection/InfoSection.tsx
  src/components/detail/InfoSection/LocationMap.tsx
  src/components/main/Postcode/Postcode.tsx
  src/components/mypage/PostUpload/PostUpload.tsx
  src/types/addressSearchType.ts
  src/types/showType.ts
  tsconfig.json
Labels: ♻️ 리팩토링, ⚙️ 개발환경, 🐞 버그, 🛠️ 기능개발

#60 bfm/page-mypage-story : 마이페이지 story 마크업 및 디자인
  src/components/common/DeleteButton/DeleteButton.tsx
  src/components/mypage/StoryItem/StoryItem.module.css
  src/components/mypage/StoryItem/StoryItem.tsx
  src/components/mypage/StoryManage/StoryManage.module.css
  src/components/mypage/StoryManage/StoryManage.tsx
Labels: ♻️ 리팩토링, 🎨 디자인

#62 bfm/page-mypage-reservation : 마이페이지 유저 예약 관리 디자인 및 마크업
  src/components/mypage/Reservation/Reservation.module.css
  src/components/mypage/Reservation/Reservation.tsx
Labels: 🎨 디자인

#59 feat/page-mypage-show-manage: 게시글 관리 페이지 리스트 GET, 후기 GET/DELETE 기능 구현
  src/apis/getMyShowList.ts
  src/apis/index.ts
  src/components/mypage/PostManage/PostManage.module.css
  src/components/mypage/PostManage/PostManage.tsx
Labels: 🙋🏻 질문, 🛠️ 기능개발

#63 feat/page-mypage-review : 마이페이지 review 조회 및 삭제 기능 추가
  src/apis/getUserReviewList.ts
  src/apis/index.ts
  src/components/mypage/ReviewManage/ReviewManage.tsx
  src/components/mypage/ReviewMypageItem/ReviewMypageItem.tsx
  src/types/reviewType.ts
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#64 feat/page-detail-reservation: 토스페이먼츠 결제 연동 및 예매 기능 구현
  package-lock.json
  package.json
  src/Router.tsx
  src/apis/index.ts
  src/apis/postReservation.ts
  src/assets/checkbox-payment.svg
  src/components/detail/ReservationForm/ReservationForm.module.css
  src/components/detail/ReservationForm/ReservationForm.tsx
  src/components/detail/ReservationModal/ReservationModal.module.css
  src/components/detail/ReservationModal/ReservationModal.tsx
  src/components/detail/ReservationPayment/ReservationPayment.tsx
  src/components/detail/ReservationPayment/style.css
  src/components/detail/index.tsx
  src/hooks/useInputs.tsx
  src/main.tsx
  src/pages/Detail/DetailPage.tsx
  src/pages/PayFail/PayFailPage.tsx
  src/pages/PaySuccess/PaySuccessPage.tsx
  src/pages/index.tsx
  src/stores/useReservationFormStore.ts
  src/types/index.ts
  src/types/showReservationInfoType.ts
  src/types/userReservationFormType.ts
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#66 feat/page-signup : 회원가입 id 중복 검증 로직 수정
  src/apis/getUserInfo.tsx
  src/pages/Signup/SignupPage.tsx
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#67 feat/page-mypage-show-update: 게시글 수정, 삭제 기능 구현
  src/Router.tsx
  src/apis/deleteShow.ts
  src/apis/index.ts
  src/apis/putShow.ts
  src/components/common/InputField/InputField.tsx
  src/components/common/RadioButtonGroup/RadioButtonGroup.tsx
  src/components/mypage/PostUpdate/PostUpdate.module.css
  src/components/mypage/PostUpdate/PostUpdate.tsx
  src/components/mypage/PostUpload/PostUpload.tsx
  src/components/mypage/ReservationForm/ReservationForm.tsx
  src/types/showReservationInfoType.ts
  src/types/showType.ts
Labels: 🛠️ 기능개발

#68 bfm/page-main: 메인페이지 디자인 및 기능 리팩토링
  src/components/common/TagInput/TagInput.css
  src/components/common/TagInput/TagInput.tsx
  src/components/common/TicketCard/TicketCard.module.css
  src/components/common/TicketCard/TicketCard.tsx
  src/components/common/index.tsx
  src/components/main/StoryUploadModal/StoryUploadModal.tsx
  src/components/main/StoryViewModalCard/StoryViewModalCard.tsx
  src/components/mainConcert/ConertListSection/ConcertListSection.tsx
  src/components/mainConcert/index.tsx
  src/components/mypage/LikeManage/LikeManage.tsx
  src/components/mypage/PostUpload/PostUpload.module.css
  src/types/storyType.ts
  src/utils/getTxtColorByBgColor.ts
  src/utils/index.ts
Labels: ♻️ 리팩토링, 🎨 디자인, 🛠️ 기능개발

#71 fix/types-etc: 타입관련 에러 및 버그 수정
  src/PrivateRoute.tsx
  src/apis/getSignUserInfo.ts
  src/apis/getUserInfo.tsx
  src/apis/index.ts
  src/components/common/Button/Button.tsx
  src/components/common/DatePicker/DatePicker.tsx
  src/components/common/Editor/Editor.tsx
  src/components/common/InputFieldGroup/InputFieldGroup.tsx
  src/components/detail/GuestAccess/GuestAccess.tsx
  src/components/detail/InfoSection/InfoSection.tsx
  src/components/detail/ReservationForm/ReservationForm.tsx
  src/components/main/Postcode/Postcode.tsx
  src/components/mypage/NavigationBar/NavigationBar.tsx
  src/components/mypage/PostManage/PostManage.tsx
  src/components/mypage/PostUpdate/PostUpdate.tsx
  src/components/mypage/Reservation/Reservation.tsx
  src/components/mypage/ReservationForm/ReservationForm.tsx
  src/components/mypage/ReviewManage/ReviewManage.tsx
  src/components/mypage/StoryManage/StoryManage.tsx
  src/hooks/useFilterSlide.tsx
  src/hooks/useInputs.tsx
  src/main.tsx
  src/pages/Error/ErrorPage.tsx
  src/pages/Mypage/Mypage.tsx
  src/pages/Signup/SignupPage.tsx
  src/types/showReservationInfoType.ts
  src/utils/dateSelect.ts
Labels: ♻️ 리팩토링, 🐞 버그

#73 feat/page-login: 로그인 시 메인 페이지로 이동
  src/pages/Login/LoginPage.tsx
Labels: ♻️ 리팩토링

#70 feat/page-reservation-manage: 관리자 마이페이지 예약관리 리스트 불러오기 기능 구현
  src/apis/getAdminReservationDetail.ts
  src/apis/getAdminReservationList.ts
  src/apis/index.ts
  src/components/common/Modal/Modal.module.css
  src/components/layouts/Header/Header.tsx
  src/components/mypage/PostManage/PostManage.module.css
  src/components/mypage/PostManage/PostManage.tsx
  src/components/mypage/ReservationListModal/ReservationListModal.module.css
  src/components/mypage/ReservationListModal/ReservationListModal.tsx
  src/components/mypage/ReservationManage/ReservationManage.module.css
  src/components/mypage/ReservationManage/ReservationManage.tsx
  src/global.css
Labels: 🎨 디자인, 🐞 버그, 🛠️ 기능개발

#69 feat/page-mypage-show-manage: 관리자 후기 삭제 모달창 닫으면 게시글 리스트 업데이트 기능 추가
  src/apis/deleteReviewAdmin.ts
  src/apis/index.ts
  src/components/common/Modal/Modal.tsx
  src/components/mypage/PostManage/PostManage.tsx
Labels: 🛠️ 기능개발

#72 feat/page-main: 일반유저가 아닌 멤버가 일반유저만 가능한 기능하려고 할 때 UserAccessModal 띄우는 기능 구현
  src/App.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/UserAccessModal/UserAccessModal.module.css
  src/components/common/UserAccessModal/UserAccessModal.tsx
  src/components/common/index.tsx
  src/components/detail/GuestAccess/GuestAccess.tsx
  src/components/detail/ReviewSection/ReviewSection.tsx
  src/components/detail/index.tsx
  src/components/main/StorySection/StorySection.tsx
  src/components/main/index.tsx
  src/components/mypage/PostUpdate/PostUpdate.tsx
  src/components/mypage/PostUpload/PostUpload.tsx
  src/components/mypage/Postcode/Postcode.tsx
  src/components/mypage/index.tsx
  src/pages/Detail/DetailPage.tsx
  src/types/showType.ts
  src/utils/index.ts
  src/utils/isNotUser.ts
Labels: ♻️ 리팩토링, 🎨 디자인, 🛠️ 기능개발

#74 fix/filters: 메인 공연페이지 카테고리 필더 제대로 동작 안하는 버그 고침
  src/components/common/Filters/Filters.tsx
Labels: 🐞 버그

#76 feat/page-mypage-story : 마이페이지 스토리 관리 API 적용
  src/apis/deleteStoryUser.ts
  src/apis/getStoryUser.ts
  src/apis/index.ts
  src/assets/null-page.png
  src/components/common/NullField/NullField.module.css
  src/components/common/NullField/NullField.tsx
  src/components/common/index.tsx
  src/components/mypage/StoryItem/StoryItem.module.css
  src/components/mypage/StoryItem/StoryItem.tsx
  src/components/mypage/StoryManage/StoryManage.module.css
  src/components/mypage/StoryManage/StoryManage.tsx
Labels: ♻️ 리팩토링, 🎨 디자인, 🛠️ 기능개발

#78 refactor/design-style: 자잘한 스타일 수정
  index.html
  public/card-image.png
  public/concert-img.jpg
  public/concert-img2.jpg
  public/concert-img3.jpg
  public/favicon.ico
  public/story-img.jpg
  src/assets/beta-logo.png
  src/components/detail/ReservationForm/ReservationForm.module.css
  src/components/detail/ReservationForm/ReservationForm.tsx
  src/components/detail/ReservationModal/ReservationModal.module.css
  src/components/detail/SubMenuSection/SubMenuSection.tsx
  src/components/layouts/Header/Header.module.css
  src/components/layouts/Header/Header.tsx
  src/components/mypage/PostUpdate/PostUpdate.module.css
  src/components/mypage/PostUpdate/PostUpdate.tsx
  src/components/mypage/PostUpload/PostUpload.module.css
  src/pages/Detail/DetaiPage.module.css
Labels: 🎨 디자인

#79 feat/page-detail-reservation : 예매할 때, 이메일 전송 및 DB 업데이트로 인한 toast 로딩 적용
  src/apis/postReservation.ts
  src/components/detail/ReservationForm/ReservationForm.tsx
Labels: 🛠️ 기능개발

#80 feat/page-mypage-show-update: 게시글 수정시 이미지, 회차관련 버그 수정 및 기타 리팩토링
  src/components/common/InputField/InputField.tsx
  src/components/detail/InfoSection/InfoSection.tsx
  src/components/detail/ReservationForm/ReservationForm.tsx
  src/components/mypage/admin/ReservationForm/ReservationForm.tsx
  src/pages/Mypage/admin/PostUpdate/PostUpdatePage.tsx
  src/pages/Mypage/admin/PostUpload/PostUploadPage.tsx
  src/types/datePickerInputType.ts
  src/types/index.ts
  src/utils/base64ToBytes.ts
  src/utils/bytesToBase64.ts
  src/utils/convertUrlToFile.ts
  src/utils/index.ts
Labels: ♻️ 리팩토링, 🐞 버그, 🛠️ 기능개발

#82 feat/page-detail: 상세 페이지에서 후기 없을 때 보여줄 화면 추가 및 스크롤 탑 기능 추가
  src/App.tsx
  src/components/detail/InfoSection/InfoSection.tsx
  src/components/detail/ReviewSection/ReviewSection.tsx
  src/components/detail/SubMenuBar/SubMenuBar.tsx
  src/components/detail/SubMenuSection/SubMenuSection.tsx
Labels: 🎨 디자인, 🐞 버그

#84 feat/page-mypage-reservation : 마이페이지 유저 예매 관리 페이지 조회 및 취소 기능 적용
  src/apis/deleteCancelShow.ts
  src/apis/getUserReservationList.ts
  src/apis/index.ts
  src/components/mypage/index.tsx
  src/components/mypage/user/ReservationItem/ReservationItem.module.css
  src/components/mypage/user/ReservationItem/ReservationItem.tsx
  src/components/mypage/user/ReservationUserModal/ReservationUserModal.module.css
  src/components/mypage/user/ReservationUserModal/ReservationUserModal.tsx
  src/pages/Mypage/user/ReservationManage/ReservationManage.tsx
  src/pages/Mypage/user/ReservationManage/ReservationManagePage.module.css
  src/pages/Mypage/user/ReservationManage/ReservationManagePage.tsx
  src/pages/index.tsx
  src/types/index.ts
  src/types/userReservationInfoType.ts
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#86 feat/page-mypage-profile : 마이페이지 프로필 관리 조회 및 수정 기능 적용
  src/apis/getUserProfile.ts
  src/apis/index.ts
  src/apis/putProfileUpdate.ts
  src/components/common/InputFieldGroup/InputFieldGroup.tsx
  src/pages/Mypage/ProfilePage/ProfilePage.tsx
  src/types/SignupBodyType.ts
Labels: 🛠️ 기능개발

#85 style/page-main: 메인페이지 컴포넌트들 스타일 수정
  src/components/common/BasicCard/BasicCard.module.css
  src/components/common/Carousel/Carousel.tsx
  src/components/common/Modal/Modal.module.css
  src/components/common/TicketCard/TicketCard.module.css
  src/components/common/TicketCard/TicketCard.tsx
  src/components/main/Banner/Banner.module.css
  src/components/main/Banner/Banner.tsx
  src/components/main/StoryCard/StoryCard.module.css
  src/components/main/StorySection/StorySection.tsx
  src/components/main/StoryUploadModal/StoryUploadModal.module.css
  src/components/main/StoryUploadModal/StoryUploadModal.tsx
  src/components/main/StoryViewModal/StoryViewModal.module.css
  src/components/main/StoryViewModalCard/StoryViewModalCard.module.css
  src/components/main/StoryViewModalCard/StoryViewModalCard.tsx
Labels: 🎨 디자인

#87 bfm/page-main: 메인페이지 전체 리팩토링
  src/components/common/Filters/Filters.tsx
  src/components/common/NullField/NullField.tsx
  src/components/layouts/NavBar/NavBar.tsx
  src/components/main/CalendarDateButton/CalendarDateButton.module.css
  src/components/main/CalendarDateButton/CalendarDateButton.tsx
  src/components/main/CalendarFilters/CalendarFilters.module.css
  src/components/main/CalendarFilters/CalendarFilters.tsx
  src/components/main/CalendarList/CalendarList.module.css
  src/components/main/CalendarList/CalendarList.tsx
  src/components/main/CalendarSection/CalendarSection.module.css
  src/components/main/CalendarSection/CalendarSection.tsx
  src/components/main/CalendarSectionSkeleton/CalendarSectionSkeleton.tsx
  src/components/main/StorySection/StorySection.tsx
  src/components/main/StorySectionSkeleton/StorySectionSkeleton.tsx
  src/components/main/StoryUploadModal/StoryUploadModal.module.css
  src/components/main/StoryUploadModal/StoryUploadModal.tsx
  src/components/main/index.tsx
  src/components/mainConcert/ConertListSection/ConcertListSection.tsx
  src/components/mainExhibition/ExhibitionListSection/ExhibitionListSection.tsx
  src/pages/Mypage/admin/PostUpdate/PostUpdatePage.tsx
  src/pages/Mypage/admin/PostUpload/PostUploadPage.tsx
  src/pages/Mypage/user/LikeManage/LikeManagePage.tsx
Labels: ♻️ 리팩토링, 🎨 디자인, 🐞 버그, 🛠️ 기능개발

#88 feat/page-signup : 회원가입 및 로그인 페이지 로고 추가, toast 적용
  src/components/common/InputField/InputField.tsx
  src/pages/Login/LoginPage.module.css
  src/pages/Login/LoginPage.tsx
  src/pages/Signup/SignupPage.module.css
  src/pages/Signup/SignupPage.tsx
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#89 feat/page-admin-reservation: ReservationListModal 이름, 이메일, 핸드폰번호, 결제날짜 추가
  src/apis/getAdminReservationDetail.ts
  src/components/mypage/admin/ReservationListModal/ReservationListModal.module.css
  src/components/mypage/admin/ReservationListModal/ReservationListModal.tsx
  src/pages/Mypage/admin/PostManage/PostManagePage.tsx
Labels: 🎨 디자인, 🐞 버그

#90 feat/page-detail-reservation: 예매 try catch문 리팩토링 및 회차 선택안했을 때 toast 알람 띄우기
  src/apis/postReservation.ts
  src/components/common/RadioButtonGroup/RadioButtonGroup.module.css
  src/components/detail/ReservationForm/ReservationForm.tsx
Labels: ♻️ 리팩토링, 🎨 디자인, 🛠️ 기능개발

#91 feat/page-main: toast alert 기능성공시 toast.info에서 toast.success로 변경
  src/components/main/StoryUploadModal/StoryUploadModal.tsx
  src/pages/Mypage/admin/PostUpdate/PostUpdatePage.tsx
  src/pages/Mypage/admin/PostUpload/PostUploadPage.tsx
Labels: ♻️ 리팩토링

#92 feat/page-mypage-show-update: 게시글 업로드, 수정 페이지 리팩토링
  src/components/common/DatePicker/DatePicker.tsx
  src/pages/Mypage/admin/PostUpdate/PostUpdatePage.tsx
  src/pages/Mypage/admin/PostUpload/PostUploadPage.tsx
  src/utils/getResizedImgFiles.ts
  src/utils/index.ts
Labels: ♻️ 리팩토링, 🐞 버그

#93 feat/page-mypage-reservation : 예매 정보 모달 창 height 제거
  src/pages/Mypage/user/ReservationManage/ReservationManagePage.tsx
Labels: 🐞 버그

#94 bfm/page-error: 에러 페이지 마크업 및 스타일
  src/assets/image-notfound.png
  src/pages/Error/ErrorPage.module.css
  src/pages/Error/ErrorPage.tsx
Labels: 🎨 디자인

#95 bfm/common: TicketCard main_image_color 없을 때 리팩토링
  src/components/common/TicketCard/TicketCard.tsx
  src/utils/getTxtColorByBgColor.ts
Labels: ♻️ 리팩토링

#96 feat/page-mypage-show-upload: 게시글 업로드 예매 폼 관련 버그 수정
  src/pages/Mypage/admin/PostUpload/PostUploadPage.tsx
Labels: 🐞 버그

#97 hotFix: PrivateRoute 일반 유저, 관리자 접근 권한 수정
  src/PrivateRoute.tsx
Labels: ♻️ 리팩토링, 🐞 버그
