Repository FESP-TEAM-1/beta-frontend, pull requests merged in 2024-01, with the labels that each got.

#99 feat/page-detail: 상세 페이지 줄바꿈 스타일 수정
  src/components/detail/InfoSection/InfoSection.module.css
Labels: 🐞 버그

#100 refactor/page-mypage-show-crud: 게시글 업로드/수정 페이지 통합
  src/Router.tsx
  src/apis/index.ts
  src/components/common/RadioButtonGroup/RadioButtonGroup.tsx
  src/components/mypage/admin/ReservationForm/ReservationForm.tsx
  src/pages/Mypage/admin/PostCRUD/PostCRUDPage.module.css
  src/pages/Mypage/admin/PostCRUD/PostCRUDPage.tsx
  src/pages/Mypage/admin/PostUpdate/PostUpdatePage.module.css
  src/pages/Mypage/admin/PostUpload/PostUploadPage.tsx
  src/pages/index.tsx
  src/types/formInputsType.ts
  src/types/index.ts
  src/types/showFormType.ts
  src/utils/index.ts
Labels: ♻️ 리팩토링

#102 refactor/axios-config : axios 자격 증명 설정
  src/main.tsx
Labels: ♻️ 리팩토링, 🐞 버그

#103 refactor/api-endpoint : API 엔드포인트 전체 URL 적용
  src/apis/deleteCancelShow.ts
  src/apis/deleteLike.ts
  src/apis/deleteReview.ts
  src/apis/deleteReviewAdmin.ts
  src/apis/deleteShow.ts
  src/apis/deleteStoryUser.ts
  src/apis/getAdminReservationDetail.ts
  src/apis/getAdminReservationList.ts
  src/apis/getBannerImages.ts
  src/apis/getMyShowList.ts
  src/apis/getReviews.ts
  src/apis/getShowInfo.tsx
  src/apis/getShowReservationInfo.tsx
  src/apis/getShows.ts
  src/apis/getSignUserInfo.ts
  src/apis/getStories.ts
  src/apis/getStoryUser.ts
  src/apis/getUserInfo.tsx
  src/apis/getUserLikeList.ts
  src/apis/getUserProfile.ts
  src/apis/getUserReservationList.ts
  src/apis/getUserReviewList.ts
  src/apis/getVerifyToken.tsx
  src/apis/patchReview.ts
  src/apis/patchUserLogin.tsx
  src/apis/patchUserLogout.tsx
  src/apis/postLike.ts
  src/apis/postReservation.ts
  src/apis/postReview.ts
  src/apis/postShow.ts
  src/apis/postStory.ts
  src/apis/putShow.ts
  src/pages/Mypage/ProfilePage/ProfilePage.tsx
  src/pages/Signup/SignupPage.tsx
Labels: ♻️ 리팩토링, 🐞 버그

#110 fix/page-main: Carousel 버그, Filter 버그 해결
  src/components/common/Filters/Filters.tsx
  src/components/main/StorySection/StorySection.tsx
  src/hooks/index.tsx
Labels: 🐞 버그

#111 refactor/resize-zoom : 페이지 Resize zoom 적용
  src/hooks/index.tsx
  src/hooks/useResizeZoom.tsx
  src/pages/Login/LoginPage.module.css
  src/pages/Login/LoginPage.tsx
  src/pages/Mypage/Mypage.module.css
  src/pages/Mypage/ProfilePage/ProfilePage.tsx
  src/pages/Signup/SignupPage.module.css
  src/pages/Signup/SignupPage.tsx
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#112 refactor/redirect-privateroute : 로그인 시 이전 위치로 이동 및 PrivateRoute 마이페이지로 이동할 때만 적용
  src/App.tsx
  src/components/common/UserAccessModal/UserAccessModal.tsx
  src/components/layouts/Header/Header.tsx
  src/pages/Login/LoginPage.tsx
Labels: ♻️ 리팩토링

#113 feat/page-detail-skeleton: 상세 페이지 컴포넌트화 및 스켈레톤 적용
  src/Router.tsx
  src/components/detail/Banner/Banner.module.css
  src/components/detail/Banner/Banner.tsx
  src/components/detail/Banner/BannerSkeleton.tsx
  src/components/detail/ButtonGroup/ButtonGroup.module.css
  src/components/detail/ButtonGroup/ButtonGroup.tsx
  src/components/detail/ButtonGroup/ButtonGroupSkeleton.tsx
  src/components/detail/InfoSection/InfoSection.tsx
  src/components/detail/InfoSection/InfoSectionSkeleton.tsx
  src/components/detail/ReviewSection/ReviewSection.tsx
  src/components/detail/ReviewSection/ReviewSectionSkeleton.tsx
  src/components/detail/SubMenuBar/SubMenuBarSkeleton.tsx
  src/components/detail/index.tsx
  src/pages/Detail/DetailPage.tsx
  src/pages/Detail/DetailPageSkeleton.tsx
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#116 refactor/rename-modules : utils, stores, type 파일, 함수 이름 변경 및 index 뽑기
  src/App.tsx
  src/apis/reservation/getUserReservationList.ts
  src/components/common/Carousel/Carousel.tsx
  src/components/common/DatePicker/DatePicker.tsx
  src/components/common/Filters/Filters.tsx
  src/components/common/InputFieldGroup/InputFieldGroup.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/TicketCard/TicketCard.tsx
  src/components/common/UserAccessModal/UserAccessModal.tsx
  src/components/detail/Banner/Banner.tsx
  src/components/detail/ButtonGroup/ButtonGroup.tsx
  src/components/detail/InfoSection/InfoSection.tsx
  src/components/detail/ReservationForm/ReservationForm.tsx
  src/components/detail/ReviewItem/ReviewItem.tsx
  src/components/detail/ReviewSection/ReviewSection.tsx
  src/components/layouts/Header/Header.tsx
  src/components/layouts/MypageNavBar/MypageNavBar.tsx
  src/components/main/Banner/Banner.tsx
  src/components/main/CalendarFilters/CalendarFilters.tsx
  src/components/main/CalendarSection/CalendarSection.tsx
  src/components/main/StorySection/StorySection.tsx
  src/components/main/StoryUploadModal/StoryUploadModal.tsx
  src/components/mypage/Profile/Profile.tsx
  src/components/mypage/admin/Postcode/Postcode.tsx
  src/components/mypage/user/ReservationUserModal/ReservationUserModal.tsx
  src/components/mypage/user/ReviewItem/ReviewItem.tsx
  src/components/mypage/user/StoryItem/StoryItem.tsx
  src/hooks/useAuth.tsx
  src/pages/Detail/DetailPage.tsx
  src/pages/Login/LoginPage.tsx
  src/pages/MainConcert/MainConcertPage.tsx
  src/pages/MainExhibition/MainExhibitionPage.tsx
  src/pages/Mypage/ProfilePage/ProfilePage.tsx
  src/pages/Mypage/admin/PostCRUD/PostCRUDPage.tsx
  src/pages/Mypage/admin/PostManage/PostManagePage.tsx
  src/pages/Mypage/admin/ReservationManage/ReservationManagePage.tsx
  src/pages/Mypage/user/ReservationManage/ReservationManagePage.tsx
  src/pages/PayFail/PayFailPage.tsx
  src/pages/PaySuccess/PaySuccessPage.tsx
  src/pages/Signup/SignupPage.tsx
  src/stores/index.ts
  src/stores/useCarouselDragStore.ts
  src/stores/useLoginStore.ts
  src/stores/useModalStore.ts
  src/stores/useReservationFormStore.ts
  src/stores/useShowInfoStore.ts
  src/types/index.ts
  src/types/signupBodyType.ts
  src/types/userInfo.ts
  src/utils/checkEmail.ts
  src/utils/checkIsNotUser.ts
  src/utils/checkIsWithinOneDay.ts
  src/utils/convertBase64ToBytes.ts
  src/utils/convertBytesToBase64.ts
  src/utils/formatDate.ts
  src/utils/formatTime.ts
  src/utils/index.ts
  src/utils/isNotUser.ts
  src/utils/selectDate.ts
  src/utils/verifyPassword.ts
Labels: ♻️ 리팩토링

#114 refactor/page-detail: 상세페이지 api 호출 관련 리팩토링 및 zustand 전역상태 삭제
  src/PrivateRoute.tsx
  src/components/detail/Banner/Banner.tsx
  src/components/detail/ButtonGroup/ButtonGroup.tsx
  src/components/detail/InfoSection/InfoSection.tsx
  src/components/detail/InfoSection/InfoSectionSkeleton.tsx
  src/components/detail/ReservationForm/ReservationForm.tsx
  src/components/detail/ReservationModal/ReservationModal.tsx
  src/components/detail/ReservationPayment/ReservationPayment.tsx
  src/hooks/index.tsx
  src/hooks/useLike.tsx
  src/pages/Detail/DetailPage.tsx
  src/pages/Mypage/admin/PostCRUD/PostCRUDPage.tsx
  src/stores/index.ts
  src/stores/useShowInfoStore.ts
  src/types/index.ts
  src/types/showReservationInfoType.ts
Labels: ♻️ 리팩토링, 🐞 버그

#118 refactor/show-upload-update-modulize: 게시글 업로드/수정 페이지 분리 및 요소 컴포넌트화 및 함수 모듈화
  src/Router.tsx
  src/components/common/InputField/InputFieldRHF.tsx
  src/components/common/RadioButtonGroup/RadioButtonGroupRHF.tsx
  src/components/common/TagInput/TagInputRHF.tsx
  src/components/mypage/admin/ImageInputSection/ImageInputSection.module.css
  src/components/mypage/admin/ImageInputSection/ImageInputSection.tsx
  src/components/mypage/admin/ReservationForm/ReservationForm.module.css
  src/components/mypage/admin/ReservationForm/ReservationForm.tsx
  src/components/mypage/admin/ShowInfoInputsSection/ShowInfoInputsSection.module.css
  src/components/mypage/admin/ShowInfoInputsSection/ShowInfoInputsSection.tsx
  src/components/mypage/admin/ShowResInfoInputsSection/ShowResInfoInputsSection.module.css
  src/components/mypage/admin/ShowResInfoInputsSection/ShowResInfoInputsSection.tsx
  src/components/mypage/index.tsx
  src/hooks/index.tsx
  src/hooks/useDeleteShowQuery.tsx
  src/hooks/useEditShowQuery.tsx
  src/hooks/useGetShowInfoQuery.tsx
  src/hooks/useGetShowResInfoQuery.tsx
  src/hooks/usePickMainImageColor.tsx
  src/hooks/useUploadShowQuery.tsx
  src/pages/Mypage/admin/PostCRUD/PostCRUDPage.module.css
  src/pages/Mypage/admin/PostCRUD/PostCRUDPage.tsx
  src/pages/Mypage/admin/PostUpdate/PostUpdatePage.module.css
  src/pages/Mypage/admin/PostUpdate/PostUpdatePage.tsx
  src/pages/Mypage/admin/PostUpload/PostUploadPage.tsx
  src/pages/index.tsx
  src/stores/index.ts
  src/stores/useImageFileStore.ts
  src/stores/useImagePreviewUrlStore.ts
  src/utils/appendResultToFormData.ts
  src/utils/appendUpdateImageToFormData.ts
  src/utils/appendUploadImageToFormData.ts
  src/utils/constant.ts
  src/utils/convertFormatForFormData.ts
  src/utils/convertRoundListToObject.ts
  src/utils/index.ts
  src/utils/setShowInfo.tsx
  src/utils/setShowResInfo.tsx
  src/utils/validateShowForm.ts
Labels: ♻️ 리팩토링

#123 refactor/error-handling: 네트워크 및 API 에러 처리
  package-lock.json
  package.json
  src/App.tsx
  src/Router.tsx
  src/components/common/Modal/Modal.tsx
  src/components/detail/Banner/Banner.tsx
  src/components/detail/ButtonGroup/ButtonGroup.tsx
  src/components/detail/InfoSection/InfoSection.tsx
  src/components/detail/ReservationForm/ReservationForm.tsx
  src/components/detail/ReservationPayment/ReservationPayment.tsx
  src/components/detail/ReviewEditForm/ReviewEditForm.tsx
  src/components/detail/ReviewForm/ReviewForm.tsx
  src/components/detail/ReviewItem/ReviewItem.tsx
  src/components/main/StoryUploadModal/StoryUploadModal.tsx
  src/components/mypage/user/ReservationUserModal/ReservationUserModal.tsx
  src/components/mypage/user/ReviewItem/ReviewItem.tsx
  src/components/mypage/user/StoryItem/StoryItem.tsx
  src/hooks/index.tsx
  src/hooks/useApiError.tsx
  src/hooks/useLike.tsx
  src/hooks/useNetworkOffline.tsx
  src/hooks/usePreventScroll.tsx
  src/main.tsx
  src/pages/Error/NetworkErrorPage.tsx
  src/pages/Main/MainPage.tsx
  src/pages/MainConcert/MainConcertPage.tsx
  src/pages/MainExhibition/MainExhibitionPage.tsx
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#125 refactor/error-handling: useGetShowResInfoQuery 훅 useQueryClient 사용
  src/hooks/useGetShowResInfoQuery.tsx
Labels: 🐞 버그

#124 refactor/page-main : 전시/공연 페이지 필터링 부분 리팩토링
  src/components/common/Filters/Filters.module.css
  src/components/common/Filters/Filters.tsx
  src/pages/MainConcert/MainConcertPage.tsx
  src/pages/MainExhibition/MainExhibitionPage.tsx
Labels: ♻️ 리팩토링

#122 refactor/page-mypage-show-manage: 후기/방명록 관리 페이지 요소 컴포넌트화 및 함수 모듈화
  src/apis/show/getAdminShowList.ts
  src/components/common/Modal/Modal.tsx
  src/components/mypage/admin/ReviewList/ReviewList.module.css
  src/components/mypage/admin/ReviewList/ReviewList.tsx
  src/components/mypage/admin/ReviewList/ReviewListSekelton.tsx
  src/components/mypage/admin/ReviewListItem/ReviewListItem.module.css
  src/components/mypage/admin/ReviewListItem/ReviewListItem.tsx
  src/components/mypage/admin/ShowList/ShowList.module.css
  src/components/mypage/admin/ShowList/ShowList.tsx
  src/components/mypage/admin/ShowListItem/ShowListItem.module.css
  src/components/mypage/admin/ShowListItem/ShowListItem.tsx
  src/components/mypage/index.tsx
  src/hooks/index.tsx
  src/hooks/useDeleteReviewQuery.tsx
  src/hooks/useGetReviewListQuery.tsx
  src/pages/Mypage/admin/PostManage/PostManagePage.module.css
  src/pages/Mypage/admin/PostManage/PostManagePage.tsx
  src/stores/index.ts
  src/stores/useShowIdStore.ts
Labels: ♻️ 리팩토링

#126 refactor/render-optimization: 메인페이지 캐러셀 렌더링 최적화
  src/components/common/Carousel/Carousel.tsx
  src/components/main/Banner/Banner.tsx
  src/components/main/StorySection/StorySection.tsx
  src/stores/index.ts
  src/stores/useCarouselDragStore.ts
Labels: ♻️ 리팩토링

#128 refactor/error-handling : toast 에러 메시지 한 번에 출력 되는 현상 수정 및 로그인 세션 만료 처리
  src/hooks/useApiError.tsx
  src/main.tsx
Labels: ♻️ 리팩토링, 🐞 버그

#137 refactor/page-signup : Timer 렌더링 문제 해결
  src/components/common/Timer/Timer.tsx
  src/hooks/index.tsx
  src/hooks/useInterval.tsx
  src/pages/Mypage/ProfilePage/ProfilePage.tsx
  src/pages/Signup/SignupPage.tsx
Labels: ♻️ 리팩토링

#138 refactor/carousel: 메인페이지 배너이미지 갯수 적을때 리팩토링
  src/assets/dummy-banner-img.svg
  src/components/common/Carousel/Carousel.module.css
  src/components/common/Carousel/Carousel.tsx
  src/components/detail/Banner/Banner.tsx
  src/components/main/Banner/Banner.module.css
  src/components/main/Banner/Banner.tsx
Labels: ♻️ 리팩토링
