Repository FESP-TEAM-1/beta-frontend, pull requests merged in 2024-02, with the labels that each got.

#136 fix/page-mypage-show-update: S3 이미지에 대해 CORS 오류 해결을 위한 쿼리 파라미터 추가
  src/components/mypage/admin/ImageInputSection/ImageInputSection.tsx
  src/hooks/usePickMainImageColor.tsx
  src/utils/appendUpdateImageToFormData.ts
Labels: 🐞 버그

#141 refactor/page-main-concert: 메인 공연/전시 페이지 필터값을 url의 queryString에 저장
  package-lock.json
  package.json
  src/apis/show/getShowList.ts
  src/components/common/Filters/Filters.tsx
  src/components/main/CalendarList/CalendarList.tsx
  src/components/mainConcert/ConertListSection/ConcertListSection.tsx
  src/components/mainExhibition/ExhibitionListSection/ExhibitionListSection.tsx
  src/pages/MainConcert/MainConcertPage.tsx
  src/pages/MainExhibition/MainExhibitionPage.tsx
  src/utils/checkIsEndDateAfterStartDate.ts
  src/utils/constant.ts
  src/utils/index.ts
Labels: ♻️ 리팩토링

#142 refactor/page-main: 메인페이지 Suspense와 ErrorBoundary 사용
  package-lock.json
  package.json
  src/components/common/BasicCard/BasicCard.module.css
  src/components/main/Banner/Banner.module.css
  src/components/main/Banner/Banner.tsx
  src/components/main/Banner/BannerSkeleton.tsx
  src/components/main/BannerSection/BannerSection.tsx
  src/components/main/CalendarList/CalendarList.tsx
  src/components/main/CalendarList/CalendarListSkeleton.tsx
  src/components/main/CalendarSectionSkeleton/CalendarSectionSkeleton.tsx
  src/components/main/StoryList/StoryList.module.css
  src/components/main/StoryList/StoryList.tsx
  src/components/main/StoryList/StoryListSkeleton.tsx
  src/components/main/StorySection/StorySection.tsx
  src/components/main/index.tsx
  src/pages/Main/MainPage.tsx
Labels: ♻️ 리팩토링

#144 bfm/story-view-modal: 스토리뷰모달 css 수정
  src/components/common/Carousel/Carousel.tsx
  src/components/common/Carousel/slick.css
  src/components/common/Modal/Modal.module.css
  src/components/main/StorySection/StorySection.tsx
  src/components/main/StoryViewModal/StoryViewModal.module.css
  src/components/main/StoryViewModal/StoryViewModal.tsx
  src/components/main/StoryViewModalCard/StoryViewModalCard.module.css
  src/components/main/StoryViewModalCard/StoryViewModalCard.tsx
Labels: ♻️ 리팩토링, 🎨 디자인

#145 bfm/header: 헤더 디자인 수정
  src/App.tsx
  src/assets/icon-join.svg
  src/assets/icon-login.svg
  src/assets/icon-logout.svg
  src/components/layouts/ButtonAfterLogin/ButtonAfterLogin.module.css
  src/components/layouts/ButtonAfterLogin/ButtonAfterLogin.tsx
  src/components/layouts/ButtonBeforeLogin/ButtonBeforeLogin.module.css
  src/components/layouts/ButtonBeforeLogin/ButtonBeforeLogin.tsx
  src/components/layouts/Header/Header.module.css
  src/components/layouts/Header/Header.tsx
  src/components/layouts/MypageSideNavBar/MypageSideNavBar.module.css
  src/components/layouts/MypageSideNavBar/MypageSideNavBar.tsx
  src/components/layouts/NavBar/NavBar.module.css
  src/components/layouts/NavBar/NavBar.tsx
  src/components/layouts/SideNavBar/SideNavBar.module.css
  src/components/layouts/SideNavBar/SideNavBar.tsx
  src/components/layouts/index.tsx
  src/global.css
Labels: ♻️ 리팩토링, 🎨 디자인

#146 refactor/payment : 결제 부분 프론트에서 백엔드로 로직 변경 및 결제 취소 기능 추가
  src/apis/index.ts
  src/apis/reservation/postPayVerification.ts
  src/apis/reservation/postReservation.ts
  src/apis/reservation/postTossConfirm.ts
  src/components/detail/ReservationForm/ReservationForm.tsx
  src/pages/PayFail/PayFailPage.tsx
  src/pages/PaySuccess/PaySuccessPage.tsx
  src/types/errorResponse.ts
  src/types/index.ts
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#143 bfm/network-error: 네트워크 에러 페이지 마크업 및 스타일
  src/pages/Error/NetworkErrorPage.tsx
Labels: 🎨 디자인

#147 refactor/page-mypage-delete : 마이페이지 삭제 시 confirm 띄우기
  src/components/mypage/user/ReviewItem/ReviewItem.tsx
  src/components/mypage/user/StoryItem/StoryItem.tsx
Labels: ♻️ 리팩토링

#148 refactor/page-main-concert: 메인 공연/전시페이지 뒤로가기 버튼 눌러도 뒤로가지 않는 버그 해결
  src/components/common/Carousel/Carousel.tsx
  src/components/common/Filters/Filters.tsx
  src/components/layouts/NavBar/NavBar.tsx
  src/components/main/CalendarSection/CalendarSection.tsx
  src/components/main/StorySection/StorySection.tsx
  src/pages/MainConcert/MainConcertPage.tsx
  src/pages/MainExhibition/MainExhibitionPage.tsx
  src/utils/constant.ts
  src/utils/index.ts
Labels: ♻️ 리팩토링, 🐞 버그

#150 fix/page-mypage : 프로필 페이지 select box 값 변경 오류 및 좋아요 관리 페이지 캐싱 값만 가져오는 오류 수정
  src/components/common/InputFieldGroup/InputFieldGroup.tsx
  src/components/mypage/user/ListItemList/LikeItemList.tsx
  src/pages/Mypage/user/LikeManage/LikeManagePage.tsx
Labels: 🐞 버그

#151 refactor/folder-structure: route관련 파일과 공통 css관련 파일을 담기위한 폴더 생성
  src/App.tsx
  src/components/detail/ReservationPayment/ReservationPayment.tsx
  src/main.tsx
  src/pages/PayFail/PayFailPage.tsx
  src/pages/PaySuccess/PaySuccessPage.tsx
  src/routes/PrivateRoute.tsx
  src/routes/Router.tsx
  src/styles/global.css
  src/styles/payment.css
  src/styles/toast.css
Labels: ♻️ 리팩토링
